package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BuildingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingAllPropertiesEquals(Building expected, Building actual) {
        assertBuildingAutoGeneratedPropertiesEquals(expected, actual);
        assertBuildingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingAllUpdatablePropertiesEquals(Building expected, Building actual) {
        assertBuildingUpdatableFieldsEquals(expected, actual);
        assertBuildingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingAutoGeneratedPropertiesEquals(Building expected, Building actual) {
        assertThat(actual)
            .as("Verify Building auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingUpdatableFieldsEquals(Building expected, Building actual) {
        assertThat(actual)
            .as("Verify Building relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBuildingUpdatableRelationshipsEquals(Building expected, Building actual) {
        // empty method
    }
}
