package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEventAllPropertiesEquals(CourseEvent expected, CourseEvent actual) {
        assertCourseEventAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEventAllUpdatablePropertiesEquals(CourseEvent expected, CourseEvent actual) {
        assertCourseEventUpdatableFieldsEquals(expected, actual);
        assertCourseEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEventAutoGeneratedPropertiesEquals(CourseEvent expected, CourseEvent actual) {
        assertThat(actual)
            .as("Verify CourseEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEventUpdatableFieldsEquals(CourseEvent expected, CourseEvent actual) {
        assertThat(actual)
            .as("Verify CourseEvent relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getExpectedStudents()).as("check expectedStudents").isEqualTo(expected.getExpectedStudents()))
            .satisfies(a -> assertThat(a.getRequiredEquipment()).as("check requiredEquipment").isEqualTo(expected.getRequiredEquipment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEventUpdatableRelationshipsEquals(CourseEvent expected, CourseEvent actual) {
        assertThat(actual)
            .as("Verify CourseEvent relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getProfessor()).as("check professor").isEqualTo(expected.getProfessor()))
            .satisfies(a -> assertThat(a.getStudentGroup()).as("check studentGroup").isEqualTo(expected.getStudentGroup()));
    }
}
