package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExamScheduleEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamScheduleEntryAllPropertiesEquals(ExamScheduleEntry expected, ExamScheduleEntry actual) {
        assertExamScheduleEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertExamScheduleEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamScheduleEntryAllUpdatablePropertiesEquals(ExamScheduleEntry expected, ExamScheduleEntry actual) {
        assertExamScheduleEntryUpdatableFieldsEquals(expected, actual);
        assertExamScheduleEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamScheduleEntryAutoGeneratedPropertiesEquals(ExamScheduleEntry expected, ExamScheduleEntry actual) {
        assertThat(actual)
            .as("Verify ExamScheduleEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamScheduleEntryUpdatableFieldsEquals(ExamScheduleEntry expected, ExamScheduleEntry actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamScheduleEntryUpdatableRelationshipsEquals(ExamScheduleEntry expected, ExamScheduleEntry actual) {
        assertThat(actual)
            .as("Verify ExamScheduleEntry relationships")
            .satisfies(a -> assertThat(a.getExam()).as("check exam").isEqualTo(expected.getExam()))
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getTimeslot()).as("check timeslot").isEqualTo(expected.getTimeslot()))
            .satisfies(a -> assertThat(a.getTimetableVersion()).as("check timetableVersion").isEqualTo(expected.getTimetableVersion()));
    }
}
