package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAllPropertiesEquals(Exam expected, Exam actual) {
        assertExamAutoGeneratedPropertiesEquals(expected, actual);
        assertExamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAllUpdatablePropertiesEquals(Exam expected, Exam actual) {
        assertExamUpdatableFieldsEquals(expected, actual);
        assertExamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamAutoGeneratedPropertiesEquals(Exam expected, Exam actual) {
        assertThat(actual)
            .as("Verify Exam auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamUpdatableFieldsEquals(Exam expected, Exam actual) {
        assertThat(actual)
            .as("Verify Exam relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getExpectedStudents()).as("check expectedStudents").isEqualTo(expected.getExpectedStudents()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExamUpdatableRelationshipsEquals(Exam expected, Exam actual) {
        assertThat(actual)
            .as("Verify Exam relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()))
            .satisfies(a -> assertThat(a.getStudentGroup()).as("check studentGroup").isEqualTo(expected.getStudentGroup()));
    }
}
