package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacultyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacultyAllPropertiesEquals(Faculty expected, Faculty actual) {
        assertFacultyAutoGeneratedPropertiesEquals(expected, actual);
        assertFacultyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacultyAllUpdatablePropertiesEquals(Faculty expected, Faculty actual) {
        assertFacultyUpdatableFieldsEquals(expected, actual);
        assertFacultyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacultyAutoGeneratedPropertiesEquals(Faculty expected, Faculty actual) {
        assertThat(actual)
            .as("Verify Faculty auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacultyUpdatableFieldsEquals(Faculty expected, Faculty actual) {
        assertThat(actual)
            .as("Verify Faculty relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacultyUpdatableRelationshipsEquals(Faculty expected, Faculty actual) {
        // empty method
    }
}
