package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfessorPreferenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorPreferenceAllPropertiesEquals(ProfessorPreference expected, ProfessorPreference actual) {
        assertProfessorPreferenceAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessorPreferenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorPreferenceAllUpdatablePropertiesEquals(ProfessorPreference expected, ProfessorPreference actual) {
        assertProfessorPreferenceUpdatableFieldsEquals(expected, actual);
        assertProfessorPreferenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorPreferenceAutoGeneratedPropertiesEquals(ProfessorPreference expected, ProfessorPreference actual) {
        assertThat(actual)
            .as("Verify ProfessorPreference auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorPreferenceUpdatableFieldsEquals(ProfessorPreference expected, ProfessorPreference actual) {
        assertThat(actual)
            .as("Verify ProfessorPreference relevant properties")
            .satisfies(a -> assertThat(a.getPreferenceType()).as("check preferenceType").isEqualTo(expected.getPreferenceType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessorPreferenceUpdatableRelationshipsEquals(ProfessorPreference expected, ProfessorPreference actual) {
        assertThat(actual)
            .as("Verify ProfessorPreference relationships")
            .satisfies(a -> assertThat(a.getProfessor()).as("check professor").isEqualTo(expected.getProfessor()))
            .satisfies(a -> assertThat(a.getTimeslot()).as("check timeslot").isEqualTo(expected.getTimeslot()));
    }
}
