package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolverJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolverJobAllPropertiesEquals(SolverJob expected, SolverJob actual) {
        assertSolverJobAutoGeneratedPropertiesEquals(expected, actual);
        assertSolverJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolverJobAllUpdatablePropertiesEquals(SolverJob expected, SolverJob actual) {
        assertSolverJobUpdatableFieldsEquals(expected, actual);
        assertSolverJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolverJobAutoGeneratedPropertiesEquals(SolverJob expected, SolverJob actual) {
        assertThat(actual)
            .as("Verify SolverJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolverJobUpdatableFieldsEquals(SolverJob expected, SolverJob actual) {
        assertThat(actual)
            .as("Verify SolverJob relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()))
            .satisfies(a -> assertThat(a.getProgressPercent()).as("check progressPercent").isEqualTo(expected.getProgressPercent()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getHardConflictCount()).as("check hardConflictCount").isEqualTo(expected.getHardConflictCount()))
            .satisfies(a -> assertThat(a.getSoftPenaltyScore()).as("check softPenaltyScore").isEqualTo(expected.getSoftPenaltyScore()))
            .satisfies(a -> assertThat(a.getBacktrackCount()).as("check backtrackCount").isEqualTo(expected.getBacktrackCount()))
            .satisfies(a ->
                assertThat(a.getDomainReductionCount()).as("check domainReductionCount").isEqualTo(expected.getDomainReductionCount())
            )
            .satisfies(a -> assertThat(a.getRuntimeMs()).as("check runtimeMs").isEqualTo(expected.getRuntimeMs()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolverJobUpdatableRelationshipsEquals(SolverJob expected, SolverJob actual) {
        // empty method
    }
}
