package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAllPropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertStudentGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAllUpdatablePropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertStudentGroupUpdatableFieldsEquals(expected, actual);
        assertStudentGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupAutoGeneratedPropertiesEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(actual)
            .as("Verify StudentGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupUpdatableFieldsEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(actual)
            .as("Verify StudentGroup relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getGroupSize()).as("check groupSize").isEqualTo(expected.getGroupSize()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentGroupUpdatableRelationshipsEquals(StudentGroup expected, StudentGroup actual) {
        assertThat(actual)
            .as("Verify StudentGroup relationships")
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()));
    }
}
