package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimetableEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableEntryAllPropertiesEquals(TimetableEntry expected, TimetableEntry actual) {
        assertTimetableEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertTimetableEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableEntryAllUpdatablePropertiesEquals(TimetableEntry expected, TimetableEntry actual) {
        assertTimetableEntryUpdatableFieldsEquals(expected, actual);
        assertTimetableEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableEntryAutoGeneratedPropertiesEquals(TimetableEntry expected, TimetableEntry actual) {
        assertThat(actual)
            .as("Verify TimetableEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableEntryUpdatableFieldsEquals(TimetableEntry expected, TimetableEntry actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableEntryUpdatableRelationshipsEquals(TimetableEntry expected, TimetableEntry actual) {
        assertThat(actual)
            .as("Verify TimetableEntry relationships")
            .satisfies(a -> assertThat(a.getTimetableVersion()).as("check timetableVersion").isEqualTo(expected.getTimetableVersion()))
            .satisfies(a -> assertThat(a.getCourseEvent()).as("check courseEvent").isEqualTo(expected.getCourseEvent()))
            .satisfies(a -> assertThat(a.getRoom()).as("check room").isEqualTo(expected.getRoom()))
            .satisfies(a -> assertThat(a.getTimeslot()).as("check timeslot").isEqualTo(expected.getTimeslot()));
    }
}
