package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimetableVersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableVersionAllPropertiesEquals(TimetableVersion expected, TimetableVersion actual) {
        assertTimetableVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertTimetableVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableVersionAllUpdatablePropertiesEquals(TimetableVersion expected, TimetableVersion actual) {
        assertTimetableVersionUpdatableFieldsEquals(expected, actual);
        assertTimetableVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableVersionAutoGeneratedPropertiesEquals(TimetableVersion expected, TimetableVersion actual) {
        assertThat(actual)
            .as("Verify TimetableVersion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableVersionUpdatableFieldsEquals(TimetableVersion expected, TimetableVersion actual) {
        assertThat(actual)
            .as("Verify TimetableVersion relevant properties")
            .satisfies(a -> assertThat(a.getVersionNumber()).as("check versionNumber").isEqualTo(expected.getVersionNumber()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a ->
                assertThat(a.getTotalHardConflicts()).as("check totalHardConflicts").isEqualTo(expected.getTotalHardConflicts())
            )
            .satisfies(a -> assertThat(a.getTotalSoftPenalty()).as("check totalSoftPenalty").isEqualTo(expected.getTotalSoftPenalty()))
            .satisfies(a -> assertThat(a.getAverageStudentGap()).as("check averageStudentGap").isEqualTo(expected.getAverageStudentGap()))
            .satisfies(a -> assertThat(a.getRoomUtilization()).as("check roomUtilization").isEqualTo(expected.getRoomUtilization()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableVersionUpdatableRelationshipsEquals(TimetableVersion expected, TimetableVersion actual) {
        assertThat(actual)
            .as("Verify TimetableVersion relationships")
            .satisfies(a -> assertThat(a.getTimetable()).as("check timetable").isEqualTo(expected.getTimetable()))
            .satisfies(a -> assertThat(a.getSolverJob()).as("check solverJob").isEqualTo(expected.getSolverJob()));
    }
}
