package com.unischeduler.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimetableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableAllPropertiesEquals(Timetable expected, Timetable actual) {
        assertTimetableAutoGeneratedPropertiesEquals(expected, actual);
        assertTimetableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableAllUpdatablePropertiesEquals(Timetable expected, Timetable actual) {
        assertTimetableUpdatableFieldsEquals(expected, actual);
        assertTimetableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableAutoGeneratedPropertiesEquals(Timetable expected, Timetable actual) {
        assertThat(actual)
            .as("Verify Timetable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableUpdatableFieldsEquals(Timetable expected, Timetable actual) {
        assertThat(actual)
            .as("Verify Timetable relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSemester()).as("check semester").isEqualTo(expected.getSemester()))
            .satisfies(a -> assertThat(a.getAcademicYear()).as("check academicYear").isEqualTo(expected.getAcademicYear()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimetableUpdatableRelationshipsEquals(Timetable expected, Timetable actual) {
        // empty method
    }
}
