export enum SolverJobStatus {
  CREATED = 'CREATED',

  VALIDATING_INPUT = 'VALIDATING_INPUT',

  BUILDING_CONFLICT_GRAPH = 'BUILDING_CONFLICT_GRAPH',

  RUNNING_WELCH_POWELL = 'RUNNING_WELCH_POWELL',

  RUNNING_AC3 = 'RUNNING_AC3',

  RUNNING_BACKTRACKING = 'RUNNING_BACKTRACKING',

  SCORING_SOFT_CONSTRAINTS = 'SCORING_SOFT_CONSTRAINTS',

  COMPLETED = 'COMPLETED',

  FAILED = 'FAILED',

  CANCELLED = 'CANCELLED',
}
